version: '2'

services:

  proxy:
    build:
      context:  ../Nginx
      dockerfile: prod-lb.dockerfile
    ports:
      - "8080:80"
    depends_on:
      - hivewebapp1
      - hivewebapp2
      - hivewebapp3
    networks:
      - hive-network

  hivewebapp1:
    build:
      context: ../
      dockerfile: Docker/prod.webapp.dockerfile
    ports:
      - "5000"
    networks: 
      - hive-network
    depends_on:
      - hivestoredb
      - redisdb

  hivewebapp2:
    build:
      context: ../
      dockerfile: Docker/prod.webapp.dockerfile
    ports:
      - "5000"
    networks: 
      - hive-network
    depends_on:
      - hivewebapp1
      - hivestoredb
      - redisdb

  hivewebapp3:
    build:
      context: ../
      dockerfile: Docker/prod.webapp.dockerfile
    ports:
      - "5000"
    networks: 
      - hive-network
    depends_on:
      - hivewebapp2
      - hivestoredb
      - redisdb
  
  hivestoredb:
    build:
      context: ../
      dockerfile: Docker/sql.dockerfile
    environment:
            SA_PASSWORD: "Samtron@1"
            ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - hive-network
    
  redisdb:
    image : redis
    ports:
       - "6379:6379"
    networks:
      - hive-network

networks:
  hive-network:
    driver: bridge