CREATE TABLE [hive].[Employee]
(
	[EMPLOYEE_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FIRST_NAME] NVARCHAR(200) NOT NULL, 
    [LAST_NAME] NVARCHAR(200) NOT NULL, 
    [ADDRESS] NVARCHAR(200) NULL, 
    [CITY] NVARCHAR(200) NULL, 
    [COUNTRY] NVARCHAR(200) NULL, 
    [CREATED_DATE] DATETIME NOT NULL, 
    [CREATED_BY] NVARCHAR(50) NOT NULL, 
    [MODIFIED_DATE] DATETIME NOT NULL, 
    [MODIFIED_BY] NVARCHAR(50) NOT NULL, 
    [IS_DELETED] BIT NOT NULL, 
    [RTS] TIMESTAMP NOT NULL
)
