CREATE TABLE [hive].[Order]
(
	[ORDER_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [EMPLOYEE_ID] INT NULL, 
    [REQUIRED_DATE] DATETIME NULL, 
    [SHIP_ADDRESS] NVARCHAR(200) NULL,
	[CREATED_DATE] DATETIME NOT NULL, 
    [CREATED_BY] NVARCHAR(50) NOT NULL, 
    [MODIFIED_DATE] DATETIME NOT NULL, 
    [MODIFIED_BY] NVARCHAR(50) NOT NULL, 
    [IS_DELETED] BIT NOT NULL, 
    [RTS] TIMESTAMP NOT NULL,
    CONSTRAINT [FK_Order_ToTable] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [hive].[EMPLOYEE]([EMPLOYEE_ID])
)
