CREATE TABLE [hive].[OrderDetails]
(
	[ORDER_DETAILS_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ORDER_ID] INT NOT NULL, 
    [PRODUCT_ID] INT NOT NULL, 
    [UNIT_PRICE] FLOAT NOT NULL, 
    [QUANTITY] FLOAT NOT NULL, 
    [DISCOUNT] FLOAT NOT NULL, 
	 [CREATED_DATE] DATETIME NOT NULL, 
    [CREATED_BY] NVARCHAR(50) NOT NULL, 
    [MODIFIED_DATE] DATETIME NOT NULL, 
    [MODIFIED_BY] NVARCHAR(50) NOT NULL, 
    [IS_DELETED] BIT NOT NULL, 
    [RTS] TIMESTAMP NOT NULL,
    CONSTRAINT [FK_OrderDetails_Order] FOREIGN KEY ([ORDER_ID]) REFERENCES [hive].[ORDER]([ORDER_ID]), 
    CONSTRAINT [FK_OrderDetails_Product] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [hive].[PRODUCT]([PRODUCT_ID])
)
