CREATE TABLE [hive].[Product]
(
	[PRODUCT_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PRODUCT_NAME] NVARCHAR(200) NOT NULL, 
    [UNIT_PRICE] FLOAT NOT NULL,
	[CREATED_DATE] DATETIME NOT NULL, 
    [CREATED_BY] NVARCHAR(50) NOT NULL, 
    [MODIFIED_DATE] DATETIME NOT NULL, 
    [MODIFIED_BY] NVARCHAR(50) NOT NULL, 
    [IS_DELETED] BIT NOT NULL, 
    [RTS] TIMESTAMP NOT NULL
)
