// <auto-generated />
using HiveStore.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HiveStore.DataAccess.Migrations
{
    [DbContext(typeof(HiveDataContext))]
    partial class HiveDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HiveStore.Entity.Employee.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<string>("Address")
                        .HasColumnName("ADDRESS")
                        .HasMaxLength(200);

                    b.Property<string>("City")
                        .HasColumnName("CITY")
                        .HasMaxLength(200);

                    b.Property<string>("Country")
                        .HasColumnName("COUNTRY")
                        .HasMaxLength(200);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnName("CREATED_BY")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FIRST_NAME")
                        .HasMaxLength(200);

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LAST_NAME")
                        .HasMaxLength(200);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnName("MODIFIED_BY")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<byte[]>("RecordTimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("RTS");

                    b.HasKey("Id");

                    b.ToTable("Employee","hive");
                });

            modelBuilder.Entity("HiveStore.Entity.Order.OrderDetailsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ORDER_DETAILS_ID");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnName("CREATED_BY")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATED_DATE");

                    b.Property<decimal>("Discount")
                        .HasColumnName("DISCOUNT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnName("MODIFIED_BY")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<int>("OrderId")
                        .HasColumnName("ORDER_ID");

                    b.Property<int>("ProductId")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnName("QUANTITY");

                    b.Property<byte[]>("RecordTimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("RTS");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnName("UNIT_PRICE");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails","hive");
                });

            modelBuilder.Entity("HiveStore.Entity.Order.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ORDER_ID");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnName("CREATED_BY")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int>("EmployeeId")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnName("MODIFIED_BY")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<byte[]>("RecordTimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("RTS");

                    b.Property<DateTime>("RequiredDate")
                        .HasColumnName("REQUIRED_DATE");

                    b.Property<string>("ShipAddress")
                        .HasColumnName("SHIP_ADDRESS");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Order","hive");
                });

            modelBuilder.Entity("HiveStore.Entity.Product.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PRODUCT_ID");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnName("CREATED_BY")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnName("MODIFIED_BY")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnName("PRODUCT_NAME")
                        .HasMaxLength(200);

                    b.Property<byte[]>("RecordTimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("RTS");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnName("UNIT_PRICE");

                    b.HasKey("Id");

                    b.ToTable("Product","hive");
                });

            modelBuilder.Entity("HiveStore.Entity.Order.OrderDetailsEntity", b =>
                {
                    b.HasOne("HiveStore.Entity.Order.OrderEntity", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HiveStore.Entity.Product.ProductEntity", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HiveStore.Entity.Order.OrderEntity", b =>
                {
                    b.HasOne("HiveStore.Entity.Employee.EmployeeEntity", "Employee")
                        .WithMany("OrderEntities")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
